//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeCluster) DeepCopyInto(out *KrumkakeCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeCluster.
func (in *KrumkakeCluster) DeepCopy() *KrumkakeCluster {
	if in == nil {
		return nil
	}
	out := new(KrumkakeCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrumkakeCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeClusterInitializationStatus) DeepCopyInto(out *KrumkakeClusterInitializationStatus) {
	*out = *in
	if in.Provisioned != nil {
		in, out := &in.Provisioned, &out.Provisioned
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeClusterInitializationStatus.
func (in *KrumkakeClusterInitializationStatus) DeepCopy() *KrumkakeClusterInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(KrumkakeClusterInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeClusterList) DeepCopyInto(out *KrumkakeClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrumkakeCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeClusterList.
func (in *KrumkakeClusterList) DeepCopy() *KrumkakeClusterList {
	if in == nil {
		return nil
	}
	out := new(KrumkakeClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrumkakeClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeClusterSpec) DeepCopyInto(out *KrumkakeClusterSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeClusterSpec.
func (in *KrumkakeClusterSpec) DeepCopy() *KrumkakeClusterSpec {
	if in == nil {
		return nil
	}
	out := new(KrumkakeClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeClusterStatus) DeepCopyInto(out *KrumkakeClusterStatus) {
	*out = *in
	in.Initialization.DeepCopyInto(&out.Initialization)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1beta2.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeClusterStatus.
func (in *KrumkakeClusterStatus) DeepCopy() *KrumkakeClusterStatus {
	if in == nil {
		return nil
	}
	out := new(KrumkakeClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeClusterTemplate) DeepCopyInto(out *KrumkakeClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeClusterTemplate.
func (in *KrumkakeClusterTemplate) DeepCopy() *KrumkakeClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(KrumkakeClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrumkakeClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeClusterTemplateList) DeepCopyInto(out *KrumkakeClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrumkakeClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeClusterTemplateList.
func (in *KrumkakeClusterTemplateList) DeepCopy() *KrumkakeClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(KrumkakeClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrumkakeClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeClusterTemplateResource) DeepCopyInto(out *KrumkakeClusterTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeClusterTemplateResource.
func (in *KrumkakeClusterTemplateResource) DeepCopy() *KrumkakeClusterTemplateResource {
	if in == nil {
		return nil
	}
	out := new(KrumkakeClusterTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeClusterTemplateSpec) DeepCopyInto(out *KrumkakeClusterTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeClusterTemplateSpec.
func (in *KrumkakeClusterTemplateSpec) DeepCopy() *KrumkakeClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(KrumkakeClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeImage) DeepCopyInto(out *KrumkakeImage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeImage.
func (in *KrumkakeImage) DeepCopy() *KrumkakeImage {
	if in == nil {
		return nil
	}
	out := new(KrumkakeImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrumkakeImage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeImageList) DeepCopyInto(out *KrumkakeImageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrumkakeImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeImageList.
func (in *KrumkakeImageList) DeepCopy() *KrumkakeImageList {
	if in == nil {
		return nil
	}
	out := new(KrumkakeImageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrumkakeImageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeImageSpec) DeepCopyInto(out *KrumkakeImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeImageSpec.
func (in *KrumkakeImageSpec) DeepCopy() *KrumkakeImageSpec {
	if in == nil {
		return nil
	}
	out := new(KrumkakeImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeImageStatus) DeepCopyInto(out *KrumkakeImageStatus) {
	*out = *in
	if in.Vultr != nil {
		in, out := &in.Vultr, &out.Vultr
		*out = new(KrumkakeImageVultrStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeImageStatus.
func (in *KrumkakeImageStatus) DeepCopy() *KrumkakeImageStatus {
	if in == nil {
		return nil
	}
	out := new(KrumkakeImageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeImageVultrStatus) DeepCopyInto(out *KrumkakeImageVultrStatus) {
	*out = *in
	if in.SnapshotState != nil {
		in, out := &in.SnapshotState, &out.SnapshotState
		*out = new(SnapshotState)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeImageVultrStatus.
func (in *KrumkakeImageVultrStatus) DeepCopy() *KrumkakeImageVultrStatus {
	if in == nil {
		return nil
	}
	out := new(KrumkakeImageVultrStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeMachine) DeepCopyInto(out *KrumkakeMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeMachine.
func (in *KrumkakeMachine) DeepCopy() *KrumkakeMachine {
	if in == nil {
		return nil
	}
	out := new(KrumkakeMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrumkakeMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeMachineInitializationStatus) DeepCopyInto(out *KrumkakeMachineInitializationStatus) {
	*out = *in
	if in.Provisioned != nil {
		in, out := &in.Provisioned, &out.Provisioned
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeMachineInitializationStatus.
func (in *KrumkakeMachineInitializationStatus) DeepCopy() *KrumkakeMachineInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(KrumkakeMachineInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeMachineList) DeepCopyInto(out *KrumkakeMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrumkakeMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeMachineList.
func (in *KrumkakeMachineList) DeepCopy() *KrumkakeMachineList {
	if in == nil {
		return nil
	}
	out := new(KrumkakeMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrumkakeMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeMachineSpec) DeepCopyInto(out *KrumkakeMachineSpec) {
	*out = *in
	in.Vultr.DeepCopyInto(&out.Vultr)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeMachineSpec.
func (in *KrumkakeMachineSpec) DeepCopy() *KrumkakeMachineSpec {
	if in == nil {
		return nil
	}
	out := new(KrumkakeMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeMachineStatus) DeepCopyInto(out *KrumkakeMachineStatus) {
	*out = *in
	in.Initialization.DeepCopyInto(&out.Initialization)
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]v1beta2.MachineAddress, len(*in))
		copy(*out, *in)
	}
	if in.Vultr != nil {
		in, out := &in.Vultr, &out.Vultr
		*out = new(KrumkakeMachineVultrStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1beta2.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeMachineStatus.
func (in *KrumkakeMachineStatus) DeepCopy() *KrumkakeMachineStatus {
	if in == nil {
		return nil
	}
	out := new(KrumkakeMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeMachineTemplate) DeepCopyInto(out *KrumkakeMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeMachineTemplate.
func (in *KrumkakeMachineTemplate) DeepCopy() *KrumkakeMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(KrumkakeMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrumkakeMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeMachineTemplateList) DeepCopyInto(out *KrumkakeMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrumkakeMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeMachineTemplateList.
func (in *KrumkakeMachineTemplateList) DeepCopy() *KrumkakeMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(KrumkakeMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrumkakeMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeMachineTemplateResource) DeepCopyInto(out *KrumkakeMachineTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeMachineTemplateResource.
func (in *KrumkakeMachineTemplateResource) DeepCopy() *KrumkakeMachineTemplateResource {
	if in == nil {
		return nil
	}
	out := new(KrumkakeMachineTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeMachineTemplateSpec) DeepCopyInto(out *KrumkakeMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeMachineTemplateSpec.
func (in *KrumkakeMachineTemplateSpec) DeepCopy() *KrumkakeMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(KrumkakeMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeMachineVultrSpec) DeepCopyInto(out *KrumkakeMachineVultrSpec) {
	*out = *in
	if in.SSHKeys != nil {
		in, out := &in.SSHKeys, &out.SSHKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeMachineVultrSpec.
func (in *KrumkakeMachineVultrSpec) DeepCopy() *KrumkakeMachineVultrSpec {
	if in == nil {
		return nil
	}
	out := new(KrumkakeMachineVultrSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrumkakeMachineVultrStatus) DeepCopyInto(out *KrumkakeMachineVultrStatus) {
	*out = *in
	if in.SubscriptionStatus != nil {
		in, out := &in.SubscriptionStatus, &out.SubscriptionStatus
		*out = new(SubscriptionStatus)
		**out = **in
	}
	if in.PowerStatus != nil {
		in, out := &in.PowerStatus, &out.PowerStatus
		*out = new(PowerStatus)
		**out = **in
	}
	if in.ServerState != nil {
		in, out := &in.ServerState, &out.ServerState
		*out = new(ServerState)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrumkakeMachineVultrStatus.
func (in *KrumkakeMachineVultrStatus) DeepCopy() *KrumkakeMachineVultrStatus {
	if in == nil {
		return nil
	}
	out := new(KrumkakeMachineVultrStatus)
	in.DeepCopyInto(out)
	return out
}
