name: Release
on:
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  publish-executable:
    name: Publish executable
    needs:
      - lint
    uses: ./.github/workflows/publish-executable.yml
    permissions:
      contents: write
    with:
      tag: ${{ github.event.release.tag_name }}

  publish-image:
    name: Publish image
    needs:
      - lint
    uses: ./.github/workflows/publish-image.yml
    permissions:
      packages: write
    with:
      tags: ${{ github.event.release.tag_name }},latest
